export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADRESS = "CART_SAVE_SHIPPING_ADRESS";
export const CART_RESET = "CART_RESET";
export const CART_REMOVE_SHIPPING_ADRESS = "CART_REMOVE_SHIPPING_ADRESS";
