export const COUPONS_CREATE_REQUEST = "COUPONS_CREATE_REQUEST";
export const COUPONS_CREATE_SUCESS = "COUPONS_CREATE_SUCESS";
export const COUPONS_CREATE_FAIL = "COUPONS_CREATE_FAIL";
export const COUPONS_CREATE_RESET = "COUPONS_CREATE_RESET";
