export const DELIVERY_CREATE_REQUEST = "DELIVERY_CREATE_REQUEST";
export const DELIVERY_CREATE_SUCESS = "DELIVERY_CREATE_SUCESS";
export const DELIVERY_CREATE_FAIL = "DELIVERY_CREATE_FAIL";

export const DELIVERY_DETAILS_REQUEST = "DELIVERY_DETAILS_REQUEST";
export const DELIVERY_DETAILS_SUCESS = "DELIVERY_DETAILS_SUCESS";
export const DELIVERY_DETAILS_FAIL = "DELIVERY_DETAILS_FAIL";
export const DELIVERY_DETAILS_RESET = "DELIVERY_DETAILS_RESET";

export const DELIVERY_DELETE_REQUEST = "DELIVERY_DELETE_REQUEST";
export const DELIVERY_DELETE_SUCESS = "DELIVERY_DELETE_SUCESS";
export const DELIVERY_DELETE_FAIL = "DELIVERY_DELETE_FAIL";

export const DELIVERY_UPDATE_REQUEST = "DELIVERY_UPDATE_REQUEST";
export const DELIVERY_UPDATE_SUCESS = "DELIVERY_UPDATE_SUCESS";
export const DELIVERY_UPDATE_FAIL = "DELIVERY_UPDATE_FAIL";
export const DELIVERY_UPDATE_RESET = "DELIVERY_UPDATE_RESET";
