export const OTP_CREATE_REQUEST = "OTP_CREATE_REQUEST";
export const OTP_CREATE_SUCESS = "OTP_CREATE_SUCESS";
export const OTP_CREATE_FAIL = "OTP_CREATE_FAIL";
export const OTP_CREATE_RESET = "OTP_CREATE_RESET";

export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCESS = "OTP_VERIFY_SUCESS";
export const OTP_VERIFY_FAIL = "OTP_VERIFY_FAIL";
export const OTP_VERIFY_RESET = "OTP_VERIFY_RESET";
