export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCESS = "PRODUCT_LIST_SUCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCESS = "PRODUCT_DELETE_SUCESS";
export const PRODUCT_DELETE_FAIL = "PRODUCT_DELETE_FAIL";
